version: '3.8'

services:
  web:
    container_name: order_service
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/orders_db
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/backend
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    restart: always

volumes:
  postgres_data:
