version: '3.8'

services:
  web:
    container_name: order_service
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/orders_db
      - REDIS_URL=redis://cache:6379/0
      - PYTHONPATH=/backend
    depends_on:
      - db
      - cache

  db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    container_name: redis_cache
    image: redis:latest
    restart: always

volumes:
  postgres_data:
